BASE_URL = "https://qa-scooter.praktikum-services.ru"
CREATE_COURIER_ENDPOINT = "/api/v1/courier"
LOGIN_COURIER_ENDPOINT = "/api/v1/courier/login"
CREATE_ORDER_ENDPOINT = "/api/v1/orders"
ORDERS_LIST_ENDPOINT = "/api/v1/orders"
ORDER_TRACK_ENDPOINT = "/api/v1/orders/track"